[REVERT] shanocast: update input openscreen hash
- reverting this else causing this issue

ra-experimental-features flakes build
[1/1/2 copied (297.4/297.5 MiB), 48.1 MiB DL] fetching source from https://cache
warning: could not update mtime for file '/home/hpal/.cache/nix/gitv3/0wkm8avk85110ri6yii0krb4fv292cl0vzf9r2r5k6x8ngkvxq13-shallow/refs/heads/main': No such file or directory
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'shanocast'
         whose name attribute is located at /home/hpal/.local/share/nix/root/nix/store/55ql4j8d47xjvfa8xggjddgfwny4n9j7-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'src' of derivation 'shanocast'
         at /home/hpal/.local/share/nix/root/nix/store/clxxzvl9x0s39fa2vbhv6psmn17pjdgv-source/cast_receiver.nix:14:11:
           13|   name = "shanocast";
           14|   inherit src;
             |           ^
           15|   NIX_CFLAGS_COMPILE =

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: NAR hash mismatch in input 'git+https://chromium.googlesource.com/openscreen.git?ref=refs/heads/main&rev=934f2462ad01c407a596641dbc611df49e2017b4&shallow=1&submodules=1', expected 'sha256-qzE/JIgpXmLsW6AiIOs1pU8eQpbyTZ1Kw5DPYqvzAYM=' but got 'sha256-Sf9mctuhcO5rXC82xkemr1/2Il5lJYX9x21vTZjngAw='